config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  resources :plans
  root 'homes#index'
  resources :teams
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # resources :issues
  resources :assigns, only: %i[index create destroy]
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  resources :users, only: :show

  resources :issues do
    collection do
      get 'search'
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  belongs_to :team
  has_many :plans, dependent: :destroy
  enum status:{未完了: 0, 進行中: 1, 完了: 2 }
  enum priority:{高: 0, 中: 1, 低: 2 }
  # mount_uploader :image, ImageUploader
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :set_q, only: %i[index search]
  before_action :set_teams, only: %i[new create edit update]

  # GET /issues or /issues.json
  def index
    @issues = @issue_q.result.order(:due_date_at)
  end

  def search
    @results = @issue_q.result
  end

  # GET /issues/1 or /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues or /issues.json
  def create
    @issue = current_user.issues.build(issue_params)
    @issue.team_id = params[:issue][:team_id]
    if @issue.save
      redirect_to issues_path(params[:issue][:team_id]), notice: "課題追加しました！"
    else
      render :new
    end
  end

  # PATCH/PUT /issues/1 or /issues/1.json
  def update
    @issue.user_id = current_user.id
    if @issue.update(issue_params)
      redirect_to issues_path(params[:issue][:team_id]), notice:"更新しました"
    else
      render :edit
    end
  end

  # DELETE /issues/1 or /issues/1.json
  def destroy
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url, notice: "Issue was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def issue_params
      params.require(:issue).permit(:title, :detail, :image, :image_cache, :cause, :goal, :gap, :due_date_at, :priority, :status, :done_flag)
    end

    def set_q
      @issue_q = Issue.ransack(params[:q])
    end

    def set_teams
      @teams = Team.all
    end

end

app/views/issues/_form.html.erb
<%= form_with(model: issue) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
        <% issue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team %>
    <%= form.collection_select(:team_id, @teams, :id, :name, include_blank: "選択して下さい" )  %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail %>
  </div>

  <div class="field">
  <%= form.label :image ,"改善前" %>
  <%= form.file_field :image %>
  </div>

  <div class="field">
  <%= form.label :image, "改善後" %>
  <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :cause %>
    <%= form.text_area :cause %>
  </div>

  <div class="field">
    <%= form.label :goal %>
    <%= form.text_area :goal %>
  </div>

  <div class="field">
    <%= form.label :gap %>
    <%= form.text_area :gap %>
  </div>

  <div class="field">
    <%= form.label :due_date_at %>
    <%= form.date_field :due_date_at %>
  </div>

  <div class="field">
    <%= form.label :status %><br>
    <%= form.select :status, Issue.statuses.keys.to_a,include_blank: "選択して下さい"  %>
  </div>

  <div class="field">
    <%= form.label :priority %><br>
    <%= form.select :priority, Issue.priorities.keys.to_a,include_blank: "選択して下さい"  %>
  </div>

  <div class="field">
    <%= form.label :done_flag %>
    <%= form.check_box :done_flag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<h1>Issues</h1>

<%= search_form_for @issue_q, url: search_issues_path do |f| %>
  <%= f.label :title_cont, '課題名' %>
  <%= f.search_field :title_cont %>
  <%= f.submit '検索' %>
<% end %>

<%= search_form_for @issue_q, url: search_issues_path do |f| %>
  <%= f.label :status, '進捗:' %>
  <%= f.radio_button :status_eq, '0' %>未完了
  <%= f.radio_button :status_eq, '1' %>進行中
  <%= f.radio_button :status_eq, '2' %>完了
  <%= f.submit '検索' %>
<% end %>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Team</th>
      <th>Title</th>
      <th><%= sort_link(@issue_q, :due_date_at, "期限日") %></th>
      <th><%= sort_link(@issue_q, :priority, "優先度") %></th>
      <th><%= sort_link(@issue_q, :status, "進捗") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <% if issue.done_flag == true %>
          <td> 完了 </td>
        <% else %>
          <td>未完了</td>
        <% end %>
          <td><%= issue.team.name %></td>
          <td><%= issue.title %></td>
          <td><%= issue.due_date_at %></td>
          <td><%= issue.priority %></td>
          <td><%= issue.status %></td>
          <td><%= link_to 'Show', issue %></td>
          <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
          <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @issue.detail %>
</p>

<p>
  <strong>改善前:</strong><br>
      <% if @issue.image?%>
        <%= image_tag @issue.image.url, size: "120x120" %>
    <% else%>
        <%= image_tag "default.jpeg", size: "120x120" %>
    <%end%>
</p>

<p>
  <strong>改善後:</strong><br>
      <% if @issue.image?%>
        <%= image_tag @issue.image.url, size: "120x120" %>
    <% else%>
        <%= image_tag "default.jpeg", size: "120x120" %>
    <%end%>
</p>

<p>
  <strong>Cause:</strong>
  <%= @issue.cause %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @issue.goal %>
</p>

<p>
  <strong>Gap:</strong>
  <%= @issue.gap %>
</p>

<p>
  <strong>Due date at:</strong>
  <%= @issue.due_date_at %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @issue.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @issue.status %>
</p>

<p>
  <strong>Done flag:</strong>
  <%= @issue.done_flag %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>